[package]
name = "glicol"
version = "0.1.0"
authors = ["chaosprint <chaosprint@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"


# [dependencies.dasp_graph]
# git = "https://github.com/chaosprint/dasp/dasp_graph"
# branch = "graph_const_generics"
# Due to https://github.com/rust-lang/cargo/issues/6513:

# You should
# `git clone https://github.com/chaosprint/dasp.git`
# `git checkout graph_const_generics`


petgraph = "0.5.1"

dasp_signal = { version = "0.11.0" }
dasp_ring_buffer = "0.11.0"
dasp_slice = "0.11.0"
dasp_interpolate = { version = "0.11.0", features = ["linear"] }

apodize = "1.0.0"
lcs-diff = "0.1.1"
gnuplot = "0.0.37"

dasp_graph = { path = "../dasp_graph" }
glicol_synth =  { path = "../synth" }
glicol_parser =  { path = "../parser" }
glicol_ext =  { path = "../ext" }