[package]
name = "glicol_synth"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["node-boxed", "node-pass", "node-sum"]
node-boxed = []
node-pass = []
node-sum = ["dasp_slice"]

[dependencies]
# glicol_macros = { path = "../macros"}
petgraph = { version = "0.6",  features = ["stable_graph"] }
dasp_slice = { version = "0.11", default-features = false, features = ["std"], optional = true }
dasp_ring_buffer = "*"
dasp_signal = "*"
dasp_interpolate = { version = "*", features = ["linear", "sinc"] }

[dev-dependencies]
gnuplot = "*"
petgraph = { version = "0.6",  features = ["stable_graph"] }
cpal = "*"
anyhow = "*"