[package]
name = "glicol_synth"
version = "0.1.0"
authors = ["chaosprint <chaosprint@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dasp_graph = { path = "../../../dasp/dasp_graph" }
dasp_signal = { version = "*" }
apodize = "1.0.0"
dasp_ring_buffer = "0.11.0"
dasp_slice = "0.11.0"
dasp_interpolate = { version = "*", features = ["linear"] }
petgraph = "*"
pest = "*"

glicol_parser = {path="../parser"}